version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: alex_website_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2368:2368"
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: your-secret-password
      database__connection__database: ghost
      # this URL will be used for links in emails, image paths, etc
      url: http://localhost:2368
      NODE_ENV: development
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      ghost_db:
        condition: service_healthy

  ghost_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-secret-password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: your-secret-password
    volumes:
      - ghost_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phoenix:
    build: .
    ports:
      - "4001:4000"
    environment:
      MIX_ENV: prod
      DATABASE_URL: "ecto://postgres:postgres@db/alex_website_prod"
      SECRET_KEY_BASE: "MxIzverHJuLFpTbUOi0k3zqsbD//gUKOwVqYeHsPpe0hA/ALxuwkB2yQHh5TUGzF"
      PHX_HOST: "localhost"
      PORT: 4000
      PHX_SERVER: "true"
      GHOST_CONTENT_API_KEY: "your-ghost-api-key"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  ghost_content:
  ghost_db_data:
